# Generated by Django 4.1.1 on 2022-10-06 14:45

import django.core.validators
from django.db import migrations, models
import notes_app.my_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link to Image')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, validators=[notes_app.my_web.models.validate_only_letters])),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, validators=[notes_app.my_web.models.validate_only_letters])),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Profile Age')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
